
try{
    sum =  1 + p
    console.log(sum)
} catch (error){
    
    const p = 10;
    sum = 1 + p;

    console.log(sum)
}

